name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: la.tex
          args:  -lualatex --file-line-error --interaction=nonstopmode
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
           name: la.pdf
           path: .
        
